services:
  dropd-slam:
    build: ./dropd-slam
    container_name: dropd_slam_container
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - GALLIUM_DRIVER=llvmpipe
      - NVIDIA_VISIBLE_DEVICES=all
    shm_size: '2gb'
    volumes:
      - ./dropd-slam:/workspace
      - ./data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix

  # fast-lio:
  #   build: ./fast-lio-ros2
  #   container_name: fast_lio_container
  #   runtime: nvidia
  #   network_mode: host
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #   volumes:
  #     - ./fast-lio-ros2:/workspace
  #     - ./data:/data
  #     - /tmp/.X11-unix:/tmp/.X11-unix